name: Build NixOS ISO

     on:
       workflow_dispatch:
       push:
         branches: [main]

     jobs:
       build:
         runs-on: ubuntu-latest
         steps:
           - name: Checkout
             uses: actions/checkout@v4

           - name: Install Nix
             uses: cachix/install-nix-action@v25
             with:
               extra_nix_config: |
                 experimental-features = nix-command flakes

           - name: Build ISO
             run: nix build .#nixosConfigurations.installer.config.system.build.isoImage

           - name: Upload ISO
             uses: actions/upload-artifact@v4
             with:
               name: nixos-installer
               path: result/iso/*.iso
