name: Build NixOS ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: nix build .#nixosConfigurations.installer.config.system.build.isoImage
    - uses: actions/upload-artifact@v4
    with:
      name: nixos-installer
      path: result/iso/*.iso
